sudo: false
language: python
install: pip install tox
matrix:
  include:
  - python: "2.6"
    env: TOX_ENV=py26
  - python: "2.7"
    env: TOX_ENV=py27
  - python: "3.5"
    env: TOX_ENV=static
  - python: "3.5"
    env: TOX_ENV=cov-travis DEPLOY=1
#  - python: "3.5"
#    env: TOX_ENV=docs
script: tox -e $TOX_ENV
#after_success:
#- test $TOX_ENV = docs && scripts/push-docs

deploy:
  # Adding a new tag automatically releases to PyPI.
  provider: pypi
  user: content-delivery-release-bot
  password:
    secure: "MgjmTev9mMDkx5P1DSWOrP3NP7vBrJmSHihhTCjog0pksgyUiHpzt9ihwX708syMzdFw4ty7QIV7vawgj23N96mghO4645adxQntbzv6nBLtSPUeVIma0eQ0caOXxibQC4OqIwKQpAftcYPK2/x4nQT2G/trngLgcUqimCRq3C/myByg9BeY5kZvcNfEc6e3MqQ8w2/q2B+PriOtUCS1gdozeqfzI52HHar9eNaT0r3H2FOgj6Qou+8325Z6vECaIZbniR3dt0jQDN/QJhpVr/+3YpNU2h2SnrI4G5cnU/Rfwpfz7nRlVP/2ay+O0ZttVyGwKvt/wDgfMchIuWV7IU0LclHOWVY8Zeiljc0up1Dw9zc6XMxPD5B1oCS1ThkI//DTVQXzwAjz3k4v9z18fS2TZkZGtadOI1ypglmPQERPqByck4+GVv96Z3BLxJ78ll4X83R685c1o/GQ38XO2wZ0hg9uRA70IK4o48VzUPem9LQGMfFu31vCUUgJyoI418Uh4YUTQLHPt6jIvvwKo1jx9h+94BuNGyL7/zMOkxNWrJin7Rbh6/aNjMjNcR8LOToLjgz5m326UZrF/UQlI2xbwYr8NyCnYULzikQ7HFFiq59SjYrTv/BsZq8+FDKdZYHvVpXoP4SYK2rMsc5u5P99YvuwTaL0Ieqit2H87Gs="
  on:
    tags: true
    # Only one of the environments in the matrix should have
    # deployments enabled. It's mostly arbitrary which one,
    # but best to select some Python 3.x so up-to-date tools
    # are used during release.
    condition: $DEPLOY = 1
  skip_existing: true