sudo: false
language: python
before_install:
  # for rpm-py-installer
  - sudo apt-get install -y rpm

install: pip install tox
matrix:
  include:
  - python: '2.7'
    env: TOX_ENV=py27
  - python: '3.8'
    env: TOX_ENV=py38
  - python: '3.9'
    env: TOX_ENV=py39
  - python: '3.9'
    env: TOX_ENV=static
  - python: '3.9'
    env: TOX_ENV=cov-travis DEPLOY=1
  - python: '3.9'
    env: TOX_ENV=docs
script: tox -e $TOX_ENV
after_success:
- test $TOX_ENV = docs && scripts/push-docs
