name: Documentation
# triggers docs push to gh-pages

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install RPM
        run: |
          sudo apt-get install -y rpm
          sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: |
          tox -e docs
          scripts/push-docs